### PR TITLE
Build docker from same repository

### PR DESCRIPTION
**Pull request by Borewit**
Build docker from repository checked out, instead of a release which may be different

Related: 
- #57 _Explain docker release version_
- https://github.com/sandreas/m4b-tool/issues/56#issuecomment-554624711

### CODE REVIEW

**Comment by sandreas** [comment]
Thank you for your pull request. Unfortunately I'm not sure, why this would be an improvement?

The existing code allows:

1. Building with an extra parameter: `docker build . --build-arg M4B_TOOL_DOWNLOAD_LINK=https://github.com/sandreas/m4b-tool/releases/download/v.0.4.1/m4b-tool.tar.gz -t m4b-tool`
2. Providing a file via `dist/` directory - `mkdir dist && cd dist && wget https://github.com/sandreas/m4b-tool/releases/download/v.0.4.1/m4b-tool.tar.gz && cd -`
3. Changing the link directly in the `Dockerfile` => `M4B_TOOL_DOWNLOAD_LINK`

Your change would:

- Remove the possibility to download an old or specific release from the internet
- Always raise an error, if the file `dist/m4b-tool.phar` does not exist


To ensure, there is no misunderstanding, let me explain the lines of the `Dockerfile` you removed (see ### lines):

```
### COPY leads to an error, when a file is not present
### add an existing file together with a wildcard will ignore the wildcard, if it is not found
ADD ./Dockerfile ./dist/m4b-tool.phar* /tmp/

RUN echo "---- INSTALL M4B-TOOL ----" \

### if local dist/m4b-tool.phar has not been copied, try to download and extract the file
    && if [ ! -f /tmp/m4b-tool.phar ]; then \
            cd /tmp/ && \
            wget "${M4B_TOOL_DOWNLOAD_LINK}" && \
            if [ ! -f /tmp/m4b-tool.phar ]; then \
                tar xzf m4b-tool*.tar.gz && rm m4b-tool*.tar.gz ;\
            fi && \
            cd - ; \
       fi \
    && mv /tmp/m4b-tool.phar /usr/local/bin/m4b-tool \
    && chmod +x /usr/local/bin/m4b-tool
```

So, did you see that? In my opinion your solution would be less flexible (it just drops existing options and contains no improvements except readability) or did i miss something?

**Comment by sandreas** [comment]
Closed due to no further feedback.

**Comment by Borewit** [comment]
Sorry, forgot about this issue @sandreas.

My aim was to build the docker image from the repository version. Downloading a different version from git is extremely confusing, and unnecessary.

**Comment by sandreas** [comment]
Yeah you are absolutely right. I'm planning to fix that as soon as `0.5.0` is out. ATM I'm working on an epub parser, that is able to embed REAL chapter names by extracting them from the according epub of an audio book. 

At least i added some hints in the documentation for now - i hope that helps you until the issues are fixed...

See https://github.com/sandreas/m4b-tool#Docker

**Comment by Borewit** [comment]
Sounds good!

I am working on some other stuff right now, but I will eventually get back to it as there are still things to improve for audio book metadata extraction.

**Pull request closed without merging**
