### PR TITLE
fixes building the Docker image on aarch64/Apple Silicon

### PR DESCRIPTION
**Pull request by christian-smith**
This fixes the Docker image building mp4v2 on Apple Silicon

### CODE REVIEW

**Comment by sandreas** [comment]
Thank you for submitting this. I have to verify this does not break other targets, but after a short review I'm pretty sure everthing is ok with this pull request.

**Comment by christian-smith** [comment]
Or a more direct solution would be to just update config.guess and config.sub in the sandreas/mp4v2 repo instead of patching those files for each docker build.

**Comment by sandreas** [comment]
Thanks for pointing this out. I will port this PR to my mp4v2 repo... it needs an update anyways :-) After its done, I'll close this PR, too.

**Comment by sandreas** [comment]
Ok, instead of using this pull request, I ported this to `mp4v2`. It would be awesome, if you could test it since atm I have no `M1` machine...

**Comment by christian-smith** [comment]
I just tested it out and it's building the image on M1 without any problems.

**Comment by sandreas** [comment]
> I just tested it out and it's building the image on M1 without any problems.

Great. So I'll close this PR without further merges required. Thank you for providing and testing this :-)

**Pull request closed without merging**
